baseURL = 'https://blog.punk.domains/'
languageCode = 'en-us'
title = 'Punk Domains Blog'
theme = "PaperMod"
googleAnalytics = 'G-FS16VGLRRR'
staticDir = ['static']
[params]
    env = "production" # to enable google analytics, opengraph, twitter-cards and schema.
    title = "Punk Domains Blog"
    description = "Punk Domains is a decentralized protocol for web3 domains."
    images = ["/cover.jpg"]
    showShareButtons = true
    showReadingTime = true
    label.icon = "picto_color.svg"
[menu]
[[menu.main]]
  name = 'Go to Punk Domains ↗'
  url = 'https://punk.domains/'